Example
....
>  ./tellduslive.py list
Devices
----------------------------------------------------------------------------------
Device  1848398                                Balkong                          On
Device  1848385                                Köket                            On
Device  1848439                                Sovrum                          Off
Device  1852182                                Vardagsrum                       On
Device  1848388                                Soffan                           On
Sensor  5658922 fineoffset temperaturehumidity Förråd                   temp  20.4
Sensor  5658922 fineoffset temperaturehumidity Förråd               humidity    51
Sensor  5168570   mandolyn temperaturehumidity Källare                  temp   8.7
Sensor  5168570   mandolyn temperaturehumidity Källare              humidity    64
Sensor  5250847   mandolyn temperaturehumidity Badrum                   temp    11
Sensor  5250847   mandolyn temperaturehumidity Badrum               humidity    50
Sensor 13007668 fineoffset temperaturehumidity Ute                      temp     1
Sensor 13007668 fineoffset temperaturehumidity Ute                  humidity    86
Sensor  5168940 fineoffset temperaturehumidity Sovrum                   temp  10.5
Sensor  5168940 fineoffset temperaturehumidity Sovrum               humidity    51
Sensor 13007664 fineoffset temperaturehumidity Gäststuga                temp   1.6
Sensor 13007664 fineoffset temperaturehumidity Gäststuga            humidity    79
Sensor  5295878   mandolyn temperaturehumidity Krypgrund                temp   4.9
Sensor  5295878   mandolyn temperaturehumidity Krypgrund            humidity    79
....


config.yml example

....
devices:
  switch1:
    name: "Switch 1"
    id: 1
    controller_id: 1
    protocol: arctech
    model: selflearning-switch
    parameters:
      house: 20077622
      unit: 0
  switch2:
    name: "Switch 2"
    id: 2
    controller_id: 1
    protocol: arctech
    model: selflearning-switch
    parameters:
      house: 20077622
      unit: 1
  sensor1:
    name: "Balkong"
    id: 3
    controller_id: 1
    protocol : "mandolyn"
    model: "temperaturehumidity"
    sensorId: 11
  sensor2:
    name: "Storgatan"
    id: 4
    controller_id: 1
    protocol : "mandolyn"
    model: "temperaturehumidity"
    sensorId: 23


controllers:
  controller1:
    name: "Tellstick net"
    id: 1
    address: 192.168.1.45
....
